name: 'Docker publish - dev'
on:
  release:
    types: [published]
  push:
    branches: [ "dev" ]
jobs:
  versioning:
    name: "Use semantic versioning"
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: "Version change"
        id: version
        uses: paulhatch/semantic-version@v5.0.2
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}-prerelease${increment}"
          change_path: "src/scpbot"
          namespace: scpbot-main
          bump_each_commit: false

          
  build:
    name: 'Build & Publish'
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
        
      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v2
        
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v2

      - name: "Login to GitHub Registry"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: string
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ github.repository_owner }}
      - name: "Build & publish scpbot"
        uses: docker/build-push-action@v4
        env:
          VERSION: ${{needs.versioning.outputs.version}}
        with:
          push: true
          tags: ghcr.io/${{ steps.string.outputs.lowercase }}/scp-bot-discord:latest-dev , ghcr.io/${{ steps.string.outputs.lowercase }}/scp-bot-discord:${{VERSION}}
          cache-from: type=gha
          cache-to: type=gha,mode=max
